### PR TITLE
Reimplement dkt without external dependencies

### PR DESCRIPTION
**Pull request by mikesep**
In retrospect, the approach of parsing the output of `docker-compose help` to create sub-commands on the fly is unnecessarily complicated and introduces unwanted dependencies and fragility to `dkt`.

I suspect this more straightforward implementation will be simpler to debug and extend in the future.

### CODE REVIEW

**Review by PatCulhane — DISMISSED** [review]

**Comment by mikesep** [comment]
This doesn't read env vars, which was one of the things I meant to test for! 🤦

**Review by PatCulhane — DISMISSED** [review]

**Comment by mikesep** [comment]
Thanks for reviewing @PatCulhane!

I squashed most of the commits together in the last force-push -- there's no file content difference from dfaba51 to 4f71547.

**Review by PatCulhane — APPROVED** [review]
Much approval

**Review by Tomkaden — APPROVED** [review]
Looks Good

**Pull request merged**
